/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.ControlChangeFont;
import java.awt.Font;
import javax.swing.JTextArea;

/**
 *
 * @author pc
 */
public class ChangeFontFrame extends javax.swing.JFrame {

    MainScreen notepadFrame;
    ControlChangeFont controlChangeFont;

    public ChangeFontFrame() {
        initComponents();
        controlChangeFont = new ControlChangeFont(this);
    }

    public ChangeFontFrame(MainScreen notepadFrame){
        this.notepadFrame = notepadFrame;
        setDefaultCloseOperation(ChangeFontFrame.DISPOSE_ON_CLOSE);
    }
    
     public void addFontList(String s)
    {
        listFont.add(s);
    }
     
     public void addStyleList(String s)
    {
        listStyle.add(s);
    }
     
     public void addSizeList(int i)
    {
        listSize.add(i+"");
    }
     
     public void setSampleTAFont(Font font)
    {
        txtTest.setFont(font);
       // System.out.println(txtTest.getText());
    }
     public void setFontText(String s)
    {
        txtFont.setText(s);
       // System.out.println(txtFont.getText());
    }
     public void setTextarea(JTextArea textarea)
    {
        controlChangeFont.setTextArea(textarea);
    }
    
     public void setStyleText(String s)
    {
        txtStyle.setText(s);
    }
      public void setSizeText(int i)
    {
        txtSize.setText(i+"");
    }
      public void SelectFontList(int i)
    {
        listFont.select(i);
    }
      public void SelectStyleList(int i)
    {
        listStyle.select(i);
    }
      public void SelectSizeList(int i)
    {
        listSize.select(i);
    }
      public String SizeText()
    {
        return txtSize.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFont = new javax.swing.JTextField();
        txtStyle = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        listFont = new java.awt.List();
        listStyle = new java.awt.List();
        listSize = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTest = new javax.swing.JTextArea();
        btnChange = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Change Font");

        txtFont.setEditable(false);
        txtFont.setText("Monospaced");

        txtStyle.setEditable(false);
        txtStyle.setText("Plain");

        txtSize.setText("13");
        txtSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSizeKeyReleased(evt);
            }
        });

        listFont.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listFontItemStateChanged(evt);
            }
        });

        listStyle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listStyleItemStateChanged(evt);
            }
        });

        listSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listSizeItemStateChanged(evt);
            }
        });
        listSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSizeActionPerformed(evt);
            }
        });

        txtTest.setEditable(false);
        txtTest.setColumns(20);
        txtTest.setRows(5);
        txtTest.setText("AaBbCc");
        jScrollPane1.setViewportView(txtTest);

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel1.setText("Font");

        jLabel2.setText("Style");

        jLabel3.setText("Size:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFont)
                                .addComponent(listFont, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStyle)
                                    .addComponent(listStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(listSize, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnChange)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listFont, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(listStyle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        controlChangeFont.Change();
    }//GEN-LAST:event_btnChangeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    controlChangeFont.ClickCancel();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listFontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listFontItemStateChanged
    String name=listFont.getSelectedItem();
        controlChangeFont.ChangeFont(name);        // TODO add your handling code here:
    }//GEN-LAST:event_listFontItemStateChanged

    private void listStyleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listStyleItemStateChanged
        int i=listStyle.getSelectedIndex();
       controlChangeFont.ChangeStyle(i);        // TODO add your handling code here:
    }//GEN-LAST:event_listStyleItemStateChanged

    private void listSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listSizeItemStateChanged
        int i=listSize.getSelectedIndex();
        controlChangeFont.ChangeSize(i+8);        // TODO add your handling code here:
    }//GEN-LAST:event_listSizeItemStateChanged

    private void txtSizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSizeKeyReleased
    if (controlChangeFont.checkSize())
        {
            controlChangeFont.ChangeSize(Integer.valueOf(txtSize.getText()));
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeKeyReleased

    private void listSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSizeActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeFontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeFontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeFontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeFontFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangeFontFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public java.awt.List listFont;
    public java.awt.List listSize;
    public java.awt.List listStyle;
    private javax.swing.JTextField txtFont;
    public javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtStyle;
    private javax.swing.JTextArea txtTest;
    // End of variables declaration//GEN-END:variables
}
